language: python

env:
- CONSTRUCT_VERSION='>=2.9,<2.10'
- CONSTRUCT_VERSION='>=2.10,<2.11'

python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'

install:
- pip install construct$CONSTRUCT_VERSION
- pip install -r requirements.txt

script:
- python setup.py test

jobs:
  exclude:
  - python: '2.7'
    env: CONSTRUCT_VERSION='>=2.10,<2.11'
  - python: '3.4'
    env: CONSTRUCT_VERSION='>=2.10,<2.11'
  - python: '3.5'
    env: CONSTRUCT_VERSION='>=2.10,<2.11'
  include:
    - stage: deploy
      script: skip
      python: '3.6'
      deploy: &pypi
        provider: pypi
        user: matwey
        password:
          secure: AWqdz752Wms7YXy3m86FigQgn9XDSUI9ArCTMh0O6hu4Irbqkoa06G+XFa+zjj8CSwEYPOpv5gG1xTB/dIC+E6IaZGIDDds7Hm8G+I4vkJs8QAjuIoXANCpxMgsnFc7dpcTzYrNJ9qlYf4fQsPtHBbtPmEHatufMOrEYbg/a14k=
        skip_existing: true
        distributions: sdist bdist_wheel
        on:
          tags: true
