name: Python

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["2.7", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
        construct-version: [">=2.9,<2.10", ">=2.10,<2.11"]
        exclude:
          - python-version: "2.7"
            construct-version: ">=2.10,<2.11"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install 'construct${{ matrix.construct-version }}'
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python setup.py test
